name: EntityCore
main: com.entitycore.EntityCore
version: 1.0.0
api-version: 1.20
authors: [Kris]
description: Modular base plugin for EntityCore

commands:
  hf:
    description: Open hopper filter GUI for the hopper you are looking at
    usage: /hf
    aliases: [hopperfilter]

permissions:
  entitycore.hopperfilters.use:
    description: Allows using hopper filter configuration (sneak-tap hopper or /hf)
    default: true
