name: EntityCore
main: com.entitycore.EntityCore
version: 1.0.0
api-version: "1.21"
authors: [Kris]
description: Modular base plugin for EntityCore

commands:
  hf:
    description: Open hopper filter menu for the hopper you're looking at
    usage: /hf
    aliases: [hopperfilter, hopper-filter, hopperfilters, hopper-filters]
  hfadmin:
    description: Opens HopperFilters operator settings.
    usage: /hfadmin

  ea:
    description: Opens the Extended Anvil GUI (must be looking at an anvil)
    usage: /ea
    aliases: [extendedanvil, extended-anvil]
  eaadmin:
    description: Opens the Extended Anvil admin GUI (Operator only)
    usage: /eaadmin

  pdc:
    description: Shows PDC (PersistentDataContainer) keys/values for the item in your main hand
    usage: /pdc [all]
    aliases: [pdatacontainer]
  prov:
    description: Provenance tools (Operator only)
    usage: /prov <markunnatural|marknatural|restamp> [source]

permissions:
  entitycore.hopperfilters.use:
    description: Allows using hopper filters
    default: true
  entitycore.hopperfilters.admin:
    description: Operator-only HopperFilters settings
    default: op

  entitycore.extendedanvil.use:
    description: Allows using the Extended Anvil GUI
    default: true
  entitycore.extendedanvil.admin:
    description: Operator-only Extended Anvil settings
    default: op

  entitycore.pdc:
    description: Allows using /pdc to inspect item PDC in chat (Operator-only by default)
    default: op
  entitycore.provenance.op:
    description: Operator-only provenance tools (/prov ...)
    default: op
  entitycore.provenance.hook:
    description: Allows provenance tagging hook for /give and /item give (Operator-only by default)
    default: op
  entitycore.provenance.alerts:
    description: Receives alerts when unnatural items are blocked from shop inventories
    default: op
