name: EntityCore
main: com.entitycore.EntityCore
version: 1.0.0
api-version: "1.21"
authors: [Kris]
description: Modular base plugin for EntityCore

commands:
  hf:
    description: Open hopper filter menu for the hopper you're looking at
    usage: /hf
    aliases: [hopperfilter, hopper-filter, hopperfilters, hopper-filters]
  hfadmin:
    description: Opens HopperFilters operator settings.
    usage: /hfadmin

  ea:
    description: Opens the Extended Anvil GUI (must be looking at an anvil)
    usage: /ea
    aliases: [extendedanvil, extended-anvil]
  eaadmin:
    description: Opens the Extended Anvil admin GUI (Operator only)
    usage: /eaadmin

permissions:
  entitycore.hopperfilters.use:
    description: Allows using hopper filters
    default: true
  entitycore.hopperfilters.admin:
    description: Operator-only HopperFilters settings
    default: op

  entitycore.extendedanvil.use:
    description: Allows using the Extended Anvil GUI
    default: true
  entitycore.extendedanvil.admin:
    description: Operator-only Extended Anvil settings
    default: op
