name: EntityCore
main: com.entitycore.EntityCore
version: 1.0.0
api-version: 1.20
authors: [Kris]
description: Modular base plugin for EntityCore

commands:
  hf:
    description: Open hopper filter menu for the hopper you're looking at
    usage: /hf
    aliases: [hopperfilter, hopper-filter, hopperfilters, hopper-filters]

permissions:
  entitycore.hopperfilters.use:
    description: Allows using hopper filters
    default: true
