name: EntityCore
main: com.entitycore.EntityCore
version: 1.0.0
api-version: "1.21"
authors: [Kris]
description: Modular base plugin for EntityCore

softdepend: [WorldGuard]

commands:
  hf:
    description: Open hopper filter menu for the hopper you're looking at
    usage: /hf
    aliases: [hopperfilter, hopper-filter, hopperfilters, hopper-filters]
  hfadmin:
    description: Opens HopperFilters operator settings.
    usage: /hfadmin

  ea:
    description: Opens the Extended Anvil GUI (must be looking at an anvil)
    usage: /ea
    aliases: [extendedanvil, extended-anvil]
  eaadmin:
    description: Opens the Extended Anvil admin GUI (Operator only)
    usage: /eaadmin

  infect:
    description: Opens Infection operator GUI (and seed controls)
    usage: /infect
    aliases: [infection]

permissions:
  entitycore.hopperfilters.use:
    description: Allows using hopper filters
    default: true
  entitycore.hopperfilters.admin:
    description: Operator-only HopperFilters settings
    default: op

  entitycore.extendedanvil.use:
    description: Allows using the Extended Anvil GUI
    default: true
  entitycore.extendedanvil.admin:
    description: Operator-only Extended Anvil settings
    default: op

  # Infection (Operator-only)
  entitycore.infection.admin:
    description: Operator-only Infection controls (GUI, toggle, seed item)
    default: op

  # FlyingAllowed
  entitycore.fly:
    description: Base permission required to fly in regions where ec-fly=ALLOW (and no vip/admin requirement is set)
    default: false
  entitycore.fly.vip:
    description: VIP flight permission for regions with ec-fly-vip=true
    default: false
  entitycore.fly.admin:
    description: Admin flight permission for regions with ec-fly-admin=true
    default: false
  entitycore.flyingallowed.bypass:
    description: Operator-only bypass for all FlyingAllowed checks (ignores DENY and requirements)
    default: op
